# Generated by Django 6.0.1 on 2026-02-21 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatuslog',
            options={'ordering': ['created_at'], 'verbose_name': 'Order Status Log', 'verbose_name_plural': 'Order Status Logs'},
        ),
        migrations.RemoveField(
            model_name='orderstatuslog',
            name='status',
        ),
        migrations.AddField(
            model_name='orderstatuslog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderstatuslog',
            name='new_status',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderstatuslog',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='orderstatuslog',
            name='old_status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
