# Generated by Django 6.0.1 on 2026-02-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('message', 'Chat Message'), ('order', 'Order Update'), ('system', 'System')], default='system', max_length=20),
        ),
    ]
